### ISSUE TITLE
Add a View errors

### ISSUE THREAD

**Issue by IstvanYbema** [punamaki/site-script-editor#1]
Hi, 
I came across an error when creating a View entry.
When leaving the view attributes to default they don't get in the json output.
But Row Limit, Is Paged, Make Default and Query are required. They should be added with default values.

Also the Row limit should be a number type and not a string.

**Comment by punamaki** [comment]
Thanks for noticing this, and sorry for the delay. This is now fixed and available in the master. It is also deployed to the sitedesigner.io.
There are other issues like this, and next bigger release should contain a mandatory field check. Schema validation should do the job in the meanwhile.
