### ISSUE TITLE
When add FieldCustomizer, ListViewCommandSet is also added

### ISSUE THREAD

**Issue by s-KaiNet** [punamaki/site-script-editor#3]
Hi, I found this issue when playing with different settings.  

Below animation demonstrates the issue:     

![field-customizer-issue](https://user-images.githubusercontent.com/10658276/50790661-9becdd80-12d0-11e9-92d9-f3e153765427.gif)  

Upon deletion it inserts a new node in column formatting as well.

**Comment by punamaki** [comment]
Yep, got it. There was one break statement missing that caused this. This is now in master and dev branches, and deployed to the site. Thanks again, valuable finding!!
